name: Run Tests

on:
  push:
    branches:
      - jesus/unit-tests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "💡 This job executes the test associated with the content manager"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install BUN
        run: npm install bun
  
      - uses: JarvusInnovations/background-action@v1
        name: Starting Server
        with:
          run: npm run start &
          wait-on: http://localhost:3000/status
          tail: true
          log-output-resume: stderr
          log-output: stderr,stdout
          log-output-if: failure
          wait-for: 1m
      - run: echo "🔎 Executing tests"
        
      - name: Run tests
        run: npm run test
